{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7adbbae",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "class KMeans:\n",
    "    def __init__(self, k=3, max_iteracoes=100):\n",
    "        self.k = k\n",
    "        self.max_iteracoes = max_iteracoes\n",
    "        self.centroides = None\n",
    "    \n",
    "    def ajustar(self, dados):\n",
    "        # 1. Inicializar centróides aleatoriamente (seleciona k pontos de dados)\n",
    "        self.centroides = dados[np.random.choice(len(dados), self.k, replace=False)]\n",
    "        \n",
    "        for _ in range(self.max_iteracoes):\n",
    "            # 2. Atribuir clusters\n",
    "            clusters = self._atribuir_clusters(dados)\n",
    "            \n",
    "            # 3. Atualizar centróides (Função a ser completada)\n",
    "            novos_centroides = self._atualizar_centroides(dados, clusters)\n",
    "            \n",
    "            # 4. Verificar convergência\n",
    "            # Se a mudança nos centróides for muito pequena (np.allclose), pare.\n",
    "            if self.centroides is not None and np.allclose(self.centroides, novos_centroides):\n",
    "                break\n",
    "            \n",
    "            self.centroides = novos_centroides\n",
    "            \n",
    "        return self # Retorna o objeto ajustado\n",
    "    \n",
    "    def _atribuir_clusters(self, dados):\n",
    "        # Calcula a distância euclidiana de cada ponto de dado para cada centróide.\n",
    "        # distancias tem forma (k, num_dados, num_dimensoes) -> (num_dados, k) após a soma.\n",
    "        \n",
    "        # O np.newaxis transforma self.centroides de (k, d) para (k, 1, d) para habilitar a subtração.\n",
    "        distancias = np.sqrt(((dados - self.centroides[:, np.newaxis])**2).sum(axis=2))\n",
    "        \n",
    "        # Retorna o índice (o ID do cluster, de 0 a k-1) do centróide mais próximo.\n",
    "        return np.argmin(distancias, axis=0)\n",
    "\n",
    "    # O método\n",
    "    def _atualizar_centroides(self, dados, clusters):\n",
    "        # Inicializa a matriz para os novos centróides\n",
    "        novos_centroides = np.zeros(self.centroides.shape)\n",
    "        \n",
    "        # Para cada cluster (de 0 a k-1)\n",
    "        for i in range(self.k):\n",
    "            # Encontra todos os pontos de dados que foram atribuídos ao cluster 'i'\n",
    "            pontos_cluster_i = dados[clusters == i]\n",
    "            \n",
    "            if len(pontos_cluster_i) > 0:\n",
    "                # O novo centróide é a média (centro) de todos os pontos de dados no cluster.\n",
    "                novos_centroides[i] = pontos_cluster_i.mean(axis=0)\n",
    "            else:\n",
    "                # Caso um cluster fique vazio, mantém o centróide anterior (ou reinicia aleatoriamente, dependendo da estratégia).\n",
    "                novos_centroides[i] = self.centroides[i]\n",
    "                \n",
    "        return novos_centroides\n",
    "\n",
    "    def prever(self, dados):\n",
    "        # Usa a mesma lógica de atribuição para prever o cluster de novos dados\n",
    "        return self._atribuir_clusters(dados)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
